"""Repository rule provisioning a hermetic Android SDK for Flutter builds.

Downloads pinned Android command-line tools and a Temurin JDK (checksummed),
accepts the SDK licenses, and installs the requested packages with sdkmanager
at fetch time (network is available to repository rules). The resulting
repository exposes an android_sdk_toolchain plus marker files that build
actions use to derive ANDROID_HOME and JAVA_HOME.
"""

_CMDLINE_TOOLS = {
    # https://dl.google.com/android/repository/commandlinetools-<os>-<build>_latest.zip
    "12700392": {
        "linux": "sha256-Mw8NsARWwm0Kfmx3k6Ai/hcOXbwDRy924SHbN8ttR0Q=",
        "mac": "sha256-QqoIgTBy+hkeLR6ZHFhozPykpW3xPoNMACck7PdjMqw=",
    },
}

_JDK = {
    "17.0.13+11": {
        "linux_aarch64": "sha256-DBf6TxTA0syekzT5lvzN3cXaRFnXaPMQXH/wKDxHv2I=",
        "linux_x64": "sha256-hoKJL8ApZZMLkCLAZvoWTdb0WO9KXcJiAWqigzOzD0k=",
        "mac_aarch64": "sha256-2LL3f3VdBugaVAg0xb4i7YbzyKUaIDlmBsB0MD+Pni0=",
        "mac_x64": "sha256-hAU1BwIAqUSmtYLSWO6EYIvSXJ8rXRzd21jfrbAZZ1o=",
    },
}

_ANDROID_SDK_LICENSES = """24333f8a63b6825ea9c5514f83c2829b004d1fee
d56f5187479451eabf01fb78af6dfcb131a6481e
"""

def _host_os(repository_ctx):
    os_name = repository_ctx.os.name.lower()
    if os_name.startswith("mac") or os_name.startswith("darwin"):
        return "mac"
    if os_name.startswith("linux"):
        return "linux"
    fail("Unsupported host OS for the Android SDK repository: {}".format(os_name))

def _host_arch(repository_ctx):
    arch = repository_ctx.os.arch.lower()
    if arch in ("aarch64", "arm64"):
        return "aarch64"
    if arch in ("x86_64", "amd64", "x64"):
        return "x64"
    fail("Unsupported host architecture for the Android SDK repository: {}".format(arch))

def _download_jdk(repository_ctx, host_os, host_arch):
    version = repository_ctx.attr.jdk_version
    if version not in _JDK:
        fail("Unknown JDK version '{}'. Known: {}".format(version, _JDK.keys()))
    key = "{}_{}".format(host_os, host_arch)
    integrity = _JDK[version].get(key)
    if not integrity:
        fail("No pinned JDK for host {}".format(key))

    url = "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-{tag}/OpenJDK17U-jdk_{arch}_{os}_hotspot_{file_ver}.tar.gz".format(
        tag = version.replace("+", "%2B"),
        arch = host_arch,
        os = host_os,
        file_ver = version.replace("+", "_"),
    )
    repository_ctx.download_and_extract(
        url = url,
        output = "jdk",
        integrity = integrity,
        stripPrefix = "jdk-" + version,
    )

    # Temurin macOS tarballs nest the JDK under Contents/Home.
    java_home = "jdk/Contents/Home" if host_os == "mac" else "jdk"
    repository_ctx.file(java_home + "/.java_home_marker", "rules_flutter JAVA_HOME marker\n")
    return java_home

def _download_cmdline_tools(repository_ctx, host_os):
    build = repository_ctx.attr.cmdline_tools_build
    if build not in _CMDLINE_TOOLS:
        fail("Unknown cmdline-tools build '{}'. Known: {}".format(build, _CMDLINE_TOOLS.keys()))
    repository_ctx.download_and_extract(
        url = "https://dl.google.com/android/repository/commandlinetools-{}-{}_latest.zip".format(host_os, build),
        integrity = _CMDLINE_TOOLS[build][host_os],
    )

def _android_sdk_repo_impl(repository_ctx):
    host_os = _host_os(repository_ctx)
    host_arch = _host_arch(repository_ctx)

    java_home = _download_jdk(repository_ctx, host_os, host_arch)
    _download_cmdline_tools(repository_ctx, host_os)

    repository_ctx.file("licenses/android-sdk-license", _ANDROID_SDK_LICENSES)

    packages = [
        "platforms;android-" + repository_ctx.attr.api_level,
        "build-tools;" + repository_ctx.attr.build_tools_version,
        "platform-tools",
    ]
    if repository_ctx.attr.ndk_version:
        packages.append("ndk;" + repository_ctx.attr.ndk_version)

    repository_ctx.report_progress("Installing Android SDK packages: {}".format(", ".join(packages)))
    result = repository_ctx.execute(
        [
            "cmdline-tools/bin/sdkmanager",
            "--sdk_root=.",
        ] + packages,
        environment = {
            "JAVA_HOME": str(repository_ctx.path(java_home)),
        },
        timeout = 3600,
    )
    if result.return_code != 0:
        fail("sdkmanager failed (code {}):\nstdout: {}\nstderr: {}".format(
            result.return_code,
            result.stdout,
            result.stderr,
        ))

    repository_ctx.file(".sdk_root_marker", "rules_flutter ANDROID_HOME marker\n")

    repository_ctx.file("BUILD.bazel", """# Generated by rules_flutter//flutter/private:android_sdk_repo.bzl
load("@rules_flutter//flutter:android_toolchain.bzl", "android_sdk_toolchain")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "sdk_files",
    srcs = glob(
        ["**"],
        exclude = [
            "BUILD.bazel",
            "REPO.bazel",
            "**/*.zip",
        ],
    ),
)

android_sdk_toolchain(
    name = "android_sdk",
    api_level = "{api_level}",
    build_tools_version = "{build_tools_version}",
    files = [":sdk_files"],
    java_home_marker = "{java_home}/.java_home_marker",
    ndk_version = "{ndk_version}",
    sdk_root_marker = ".sdk_root_marker",
)

toolchain(
    name = "toolchain",
    exec_compatible_with = [
        "@platforms//os:{platform_os}",
        "@platforms//cpu:{platform_cpu}",
    ],
    toolchain = ":android_sdk",
    toolchain_type = "@rules_flutter//flutter:android_sdk_toolchain_type",
)
""".format(
        api_level = repository_ctx.attr.api_level,
        build_tools_version = repository_ctx.attr.build_tools_version,
        ndk_version = repository_ctx.attr.ndk_version,
        java_home = java_home,
        platform_os = "macos" if host_os == "mac" else "linux",
        platform_cpu = "arm64" if host_arch == "aarch64" else "x86_64",
    ))

android_sdk_repository = repository_rule(
    implementation = _android_sdk_repo_impl,
    attrs = {
        "api_level": attr.string(
            default = "36",
            doc = "Android platform API level to install (platforms;android-<n>).",
        ),
        "build_tools_version": attr.string(
            default = "35.0.0",
            doc = "build-tools version to install.",
        ),
        "ndk_version": attr.string(
            default = "",
            doc = "Optional NDK version to install (large download; ~4GB unpacked).",
        ),
        "cmdline_tools_build": attr.string(
            default = "12700392",
            doc = "Pinned Android command-line tools build number.",
        ),
        "jdk_version": attr.string(
            default = "17.0.13+11",
            doc = "Pinned Temurin JDK version bundled for sdkmanager and Gradle.",
        ),
    },
    doc = """Provisions a hermetic Android SDK (with bundled JDK) at fetch time.

Note: the cmdline-tools and JDK archives are integrity-checked; packages
installed by sdkmanager are fetched over TLS from dl.google.com but are not
content-pinned (sdkmanager does not expose hashes). A follow-up may replace
sdkmanager with direct pinned zip downloads.""",
)
