"""Mirror of Flutter SDK release info

This file is automatically generated by scripts/update_flutter_versions.sh
To update: bazel run //tools:update_flutter_versions

Flutter SDK releases are available at:
https://storage.googleapis.com/flutter_infra_release/releases/stable/{platform}/
"""

# The integrity hashes are computed from Flutter's official SHA-256 checksums
# and converted to SRI format for Bazel integrity checking
TOOL_VERSIONS = {
    "3.24.0": {
        "macos": "sha256-lKtzuIpKmWxOuTBkSDjQhjkYy8SgOagUTMr+Lhys0wQ=",
        "linux": "sha256-1SpdEvF9i8+GjRzMAf4Pf/sFtT2WKKohsHoY+dM2IfI=",
        "windows": "sha256-aNvLaLOhk6Z/aZJL+fpI6ONOyMqULeqRLSD5EG0Hqbk=",
    },
    "3.27.0": {
        "macos": "sha256-2lSPEFvq82gSqkhfIcsUApQECQmnYYKlJWCF0ZarqxU=",
        "linux": "sha256-wFkhM8xh18TUJ2IofehLfguv3T/WLrJuqts0LEMJ1UE=",
        "windows": "sha256-wVi6+1yXvYHj0pNq9XEds7nOUZ3uXzrATB+soFdsqio=",
    },
    "3.29.0": {
        "macos": "sha256-07LQG39nE/Oow8UepKT7d6J3XPxpcI9gi9L/aISTJCo=",
        "linux": "sha256-H5jz3ikx4dCXlw5W32kbA19oQKoFvmMsT6KiKYx8/dg=",
        "windows": "sha256-CwCAkS+Fa2aEOiBhvHPnOrHqILaPBoEAlW2ml4O0ynA=",
    },
}
