name: hello_world
description: A simple Flutter hello world app for testing

version: 1.0.0+1

environment:
  flutter: ">=3.24.0"
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fixnum: ^1.1.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
