import 'package:codegen_app/generated/assets.gen.dart';
import 'package:codegen_app/model.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('copyWith extension is generated by build_runner', () {
    const greeting = Greeting(message: 'hello');
    final copy = greeting.copyWith(count: 2);
    expect(copy.message, 'hello');
    expect(copy.count, 2);
  });

  test('flutter_gen asset constants are generated by build_runner', () {
    expect(Assets.hello, 'assets/hello.txt');
  });
}
