"""Unit tests for the SDK workspace-lock seed in package_generation.bzl."""

load("@bazel_skylib//lib:unittest.bzl", "asserts", "unittest")
load("//flutter/private:package_generation.bzl", "filter_lock_to_hosted")

# Shaped like flutter/pubspec.lock in a Flutter >= 3.35 archive: mostly hosted
# entries, plus the git and sdk sources that only resolve inside the monorepo.
_WORKSPACE_LOCK = """# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  assets_for_android_views:
    dependency: transitive
    description:
      path: "dev/integration_tests/assets_for_android_views"
      ref: "64d0f605"
      url: "https://github.com/flutter/assets-for-api-docs.git"
    source: git
    version: "1.0.0"
  process:
    dependency: "direct main"
    description:
      name: process
      sha256: c6248e45
      url: "https://pub.dev"
    source: hosted
    version: "5.0.5"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  vm_service:
    dependency: "direct main"
    description:
      name: vm_service
      sha256: "5f37239c"
      url: "https://pub.dev"
    source: hosted
    version: "15.0.2"
sdks:
  dart: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"
"""

def _hosted_entries_kept_test_impl(ctx):
    env = unittest.begin(ctx)
    seeded = filter_lock_to_hosted(_WORKSPACE_LOCK)

    # The pins consumers resolve against survive in full: dropping the sha256
    # or the url would make pub re-resolve the entry and reintroduce the drift
    # this seed exists to prevent.
    asserts.equals(
        env,
        """# Generated by rules_flutter from the Flutter SDK workspace lock.
packages:
  process:
    dependency: "direct main"
    description:
      name: process
      sha256: c6248e45
      url: "https://pub.dev"
    source: hosted
    version: "5.0.5"
  vm_service:
    dependency: "direct main"
    description:
      name: vm_service
      sha256: "5f37239c"
      url: "https://pub.dev"
    source: hosted
    version: "15.0.2"
""",
        seeded,
    )
    return unittest.end(env)

def _non_hosted_sources_dropped_test_impl(ctx):
    env = unittest.begin(ctx)
    seeded = filter_lock_to_hosted(_WORKSPACE_LOCK)

    # git and sdk entries name monorepo-internal packages that a standalone
    # SDK package never resolves; carrying them over would fail the solve.
    asserts.false(
        env,
        "assets_for_android_views" in seeded,
        "git-sourced workspace members must not be seeded",
    )
    asserts.false(env, "source: git" in seeded, "no git sources may be seeded")
    asserts.false(env, "sky_engine" in seeded, "sdk-sourced entries must not be seeded")

    # The workspace's own SDK range would make pub discard the whole lockfile
    # for a package whose `environment:` is narrower.
    asserts.false(env, "sdks:" in seeded, "the sdks block must not be seeded")
    return unittest.end(env)

def _no_lock_test_impl(ctx):
    env = unittest.begin(ctx)

    # Pre-workspace Flutter releases ship no lock at all and pin exact
    # versions in every package pubspec: nothing to seed, and seeding an
    # empty lockfile would be worse than seeding none.
    asserts.equals(env, "", filter_lock_to_hosted(""))
    asserts.equals(env, "", filter_lock_to_hosted("packages:\nsdks:\n  dart: \">=3.0.0 <4.0.0\"\n"))
    asserts.equals(
        env,
        "",
        filter_lock_to_hosted(_WORKSPACE_LOCK.replace("source: hosted", "source: git")),
    )
    return unittest.end(env)

_hosted_entries_kept_test = unittest.make(_hosted_entries_kept_test_impl)
_non_hosted_sources_dropped_test = unittest.make(_non_hosted_sources_dropped_test_impl)
_no_lock_test = unittest.make(_no_lock_test_impl)

def sdk_lock_test_suite(name):
    unittest.suite(
        name,
        _hosted_entries_kept_test,
        _no_lock_test,
        _non_hosted_sources_dropped_test,
    )
