# See https://github.com/bazel-contrib/publish-to-bcr#a-note-on-release-automation
fixedReleaser:
  login: SpencerC
  email: spencer@ggx.trade

# Both modules are published from the same repository and release tag.
moduleRoots: [".", "gazelle"]
